[package]
name = "tower-lol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
http = "0.2.9"
http-body = "0.4.5"
lol_html = "1.0.0"
pin-project-lite = "0.2.9"
tower = "0.4.13"
