[package]
name = "tower-lol"
version = "0.1.0-pre1"
edition = "2021"

[dependencies]
bytes = "1.4.0"
http = "0.2.9"
http-body = "0.4.5"
lol_html = "1.1.1"
pin-project-lite = "0.2.13"
tower = "0.4.13"
