[package]
name = "tower-htmx2"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
http = "1.1.0"
http-body = "1.0.1"
http-body-util = "0.1.2"
lol_html = "1.2.1"
pin-project-lite = "0.2.14"
tower = "0.5.1"
