[package]
name = "tower-htmx"
version = "0.1.0-pre1"
edition = "2021"

[dependencies]
form_urlencoded = "1.2.1"
http = "1.1.0"
http-body = "1.0.1"
percent-encoding = "2.3.1"
tower = "0.5.1"
tower-lol = { version = "0.1.0-pre1", path = "../tower-lol" }
